# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BBQ_iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '10.0'
  use_frameworks!

pod 'Kingfisher', '~> 5.0.1'
pod 'Moya'
pod 'Moya/ReactiveSwift'
pod 'Moya/RxSwift'
pod 'Moya-ObjectMapper'
pod 'Moya-ObjectMapper/RxSwift'
pod 'Moya-ObjectMapper/ReactiveSwift'
pod 'ObjectMapper', '~> 3.4.2'
pod 'IQKeyboardManagerSwift', '~> 6.2.0'
pod 'KeychainSwift', '~> 13.0.0'
pod 'SwiftyUserDefaults', '~> 3.0.1'
pod 'PopupDialog', '~> 0.9.2'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'NVActivityIndicatorView', '~> 4.5.1'
pod 'SwiftEventBus', :tag => '5.0.1', :git => 'https://github.com/cesarferreira/SwiftEventBus.git'
pod 'lottie-ios'

end
