#if !defined(___DSTOOLKIT_IPHONE_ERRCODE_H___)
#define ___DSTOOLKIT_IPHONE_ERRCODE_H___

#define XSIGN_DSTK_OK									0

#define XSIGN_DSTK_ERR_ALREADY_INITIALIZED					1000
#define XSIGN_DSTK_ERR_API_NOT_INITIALIZED					1001
#define XSIGN_DSTK_ERR_MEM_ALLOC							1002
#define XSIGN_DSTK_ERR_SET_WORK_DIR							1003
#define	XSIGN_DSTK_ERR_INVALID_INPUT						1004
#define XSIGN_DSTK_ERR_INSUFFICIENT_ALLOC_SIZE				1005
#define XSIGN_DSTK_ERR_NO_XSIGN_DSTK_ERR_MSG				1006
#define XSIGN_DSTK_ERR_LICENSE_FILE_NOT_EXIST				1007
#define XSIGN_DSTK_ERR_LICENSE_FILE_WRONG					1008
#define XSIGN_DSTK_ERR_LICENSE_FILE_ISNOT_FOR_DSTOOKIT		1009
#define XSIGN_DSTK_ERR_LICENSE_FILE_ISNOT_FOR_SYSTEM		1010
#define XSIGN_DSTK_ERR_LICENSE_FILE_EXPIRED					1011
#define XSIGN_DSTK_ERR_SET_CONFIG_FILE						1012
#define XSIGN_DSTK_ERR_NOT_SUPPORTED_FUNCTION				1013
#define XSIGN_DSTK_ERR_GEN_LICENSE_CACHE					1014
#define XSIGN_DSTK_ERR_SAVE_LICENSE_CACHE					1015
#define XSIGN_DSTK_ERR_LICENSE_FILE_VALIDITY				1016
#define XSIGN_DSTK_ERR_TIME_OUT								1017
#define XSIGN_DSTK_ERR_LICENSE_CHECK_FAILED					1018
#define XSIGN_DSTK_ERR_LICENSE_MODIFIED						1019
#define XSIGN_DSTK_ERR_MODULE_PATH_EMPTY					1020
#define XSIGN_DSTK_ERR_INPUT_MODULE_PATH					1021
#define XSIGN_DSTK_ERR_LOAD_MODULE							1022
#define XSIGN_DSTK_ERR_MODULE_MODIFIED						1023

#define XSIGN_DSTK_ERR_WRONG_CERT							1500
#define XSIGN_DSTK_ERR_LOAD_CERT							1501
#define XSIGN_DSTK_ERR_NOT_EXIST_FIELD						1502
#define XSIGN_DSTK_ERR_NOT_EXIST_CRL_DP						1503
#define XSIGN_DSTK_ERR_WRONG_CRLDP							1504
#define XSIGN_DSTK_ERR_SAVE_CERT_PATH						1505
#define XSIGN_DSTK_ERR_FAIL_CONSTRUCT_PATH					1506
#define XSIGN_DSTK_ERR_SET_TRUST_ROOT_CERT					1507
#define XSIGN_DSTK_ERR_WRONG_TRUST_ROOT_CERTS				1508
#define XSIGN_DSTK_ERR_SAVE_CTL								1509
#define XSIGN_DSTK_ERR_FAIL_OPTAIN_CTL						1510
#define XSIGN_DSTK_ERR_NOT_TRUST_ROOT_CERT					1511
#define XSIGN_DSTK_ERR_WRONG_CTL							1512
#define XSIGN_DSTK_ERR_WRONG_CTL_VALIDITY					1513
#define XSIGN_DSTK_ERR_EXPIRED_CTL							1514
#define XSIGN_DSTK_ERR_NOT_EXIST_CTL_SIGNER_CERT			1515
#define XSIGN_DSTK_ERR_NOT_TRUST_CTL_ISSUER					1516
#define XSIGN_DSTK_ERR_PATH_VALIDATION						1517
#define XSIGN_DSTK_ERR_PATH_VALIDATION_VALIDITY				1518
#define XSIGN_DSTK_ERR_PATH_VALIDATION_KEY_USAGE			1519
#define XSIGN_DSTK_ERR_PATH_VALIDATION_BASIC_CONSTS			1520
#define XSIGN_DSTK_ERR_PATH_VALIDATION_NAME_CONSTS			1521
#define XSIGN_DSTK_ERR_PATH_VALIDATION_CERT_POLICIES		1522
#define XSIGN_DSTK_ERR_SAVE_CRL								1523
#define XSIGN_DSTK_ERR_HOLDED_CERT							1524
#define XSIGN_DSTK_ERR_REVOKED_CERT							1525
#define XSIGN_DSTK_ERR_UNKNOWN_CERT							1526
#define XSIGN_DSTK_ERR_CONNECT_OCSP							1527
#define XSIGN_DSTK_ERR_OCSP_REQ_SEND						1528
#define XSIGN_DSTK_ERR_OCSP_MSG_REC							1529
#define XSIGN_DSTK_ERR_WRONG_CRL							1530
#define XSIGN_DSTK_ERR_WRONG_CRL_VALIDITY					1531
#define XSIGN_DSTK_ERR_EXPIRED_CRL							1532
#define XSIGN_DSTK_ERR_COMPOSE_OCSP_REQ_MSG					1533
#define XSIGN_DSTK_ERR_WRONG_OCSP_RES_MSG					1534
#define XSIGN_DSTK_ERR_OCSP_REQ_NOT_GRANTED					1535
#define XSIGN_DSTK_ERR_DIFFERENT_NONCE						1536
#define XSIGN_DSTK_ERR_MAKE_CAPUBS							1537
#define XSIGN_DSTK_ERR_FAIL_OPTAIN_CERT_PATH				1538
#define XSIGN_DSTK_ERR_NOT_EXIST_OCSP_INFO					1539
#define XSIGN_DSTK_ERR_EXPIRED_CERT							1540
#define XSIGN_DSTK_ERR_NOT_CERT								1541
#define XSIGN_DSTK_ERR_FAIL_OPTAIN_CRL						1542 
#define XSIGN_DSTK_ERR_WRONG_CAPUBS							1543
#define XSIGN_DSTK_ERR_ERR_SET_CAPUBS						1544

#define XSIGN_DSTK_ERR_WRONG_PRIKEY							2000
#define XSIGN_DSTK_ERR_WRONG_ENC_PRIKEY						2001
#define XSIGN_DSTK_ERR_ENCRYPT_PRIKEY						2002
#define XSIGN_DSTK_ERR_NOT_MATCHED_KEY_PAIR					2003
#define XSIGN_DSTK_ERR_WRONG_PASSWORD						2004

#define XSIGN_DSTK_ERR_CONNECT_IVS							2100
#define XSIGN_DSTK_ERR_IVS_REQ_SEND							2101
#define XSIGN_DSTK_ERR_IVS_MSG_REC							2102
#define XSIGN_DSTK_ERR_WRONG_IVS_RES_MSG					2103
#define XSIGN_DSTK_ERR_NOT_SERVICE_CERT						2104
#define XSIGN_DSTK_ERR_SYSTEM_INTERNAL_ERROR				2105
#define XSIGN_DSTK_ERR_REQUESTER_CERT_REVOKED				2106
#define XSIGN_DSTK_ERR_REQUESTER_CERT_INVALID				2107
#define XSIGN_DSTK_ERR_REQUESTER_CERT_UNAUTHORIZED			2109
#define XSIGN_DSTK_ERR_REQ_MSG_FORMAT						2110
#define XSIGN_DSTK_ERR_UNKNOWN_IVS_CODE						2111
#define XSIGN_DSTK_ERR_FAIL_READ_IVS_IP_FROM_CONF_FILE		2112
#define XSIGN_DSTK_ERR_FAIL_READ_IVS_PORT_FROM_CONF_FILE	2113
#define XSIGN_DSTK_ERR_FAIL_READ_IVS_CERT_FROM_CONF_FILE	2114
#define XSIGN_DSTK_ERR_FAIL_GET_IVS_KM_CERT_FROM_LDAP		2115
#define XSIGN_DSTK_ERR_FAIL_GET_IVS_SIGN_CERT_FROM_LDAP		2116
#define XSIGN_DSTK_ERR_NOT_TRUST_IVS_CERT					2117

#define XSIGN_DSTK_ERR_READ_FILE							2500
#define XSIGN_DSTK_ERR_SAVE_FILE							2501
#define XSIGN_DSTK_ERR_EMPTY_FILE							2502
#define XSIGN_DSTK_ERR_SAVE_CERT							2503
#define XSIGN_DSTK_ERR_READ_CERT							2504
#define XSIGN_DSTK_ERR_DELETE_CERT							2505
#define XSIGN_DSTK_ERR_SAVE_PRIKEY							2506
#define XSIGN_DSTK_ERR_READ_PRIKEY							2507
#define XSIGN_DSTK_ERR_DELETE_PRIKEY						2508
#define XSIGN_DSTK_ERR_ALREADY_LOADED						2509
#define XSIGN_DSTK_ERR_FAIL_LOAD_LIBRARY					2510
#define XSIGN_DSTK_ERR_FAIL_FREE_LIBRARY					2511
#define XSIGN_DSTK_ERR_FAIL_LOAD_FUNCTION					2512
#define XSIGN_DSTK_ERR_LOAD_LIBRARY							2513
#define XSIGN_DSTK_ERR_CHECK_CONNECTION					    2514
#define XSIGN_DSTK_ERR_WRONG_PIN							2515
#define XSIGN_DSTK_ERR_SAVE_PUBKEY						    2516
#define XSIGN_DSTK_ERR_DELETE_PUBKEY						2517
#define XSIGN_DSTK_ERR_SAVE_RANDOM_FOR_VID				    2518
#define XSIGN_DSTK_ERR_READ_RANDOM_FOR_VID				    2519
#define XSIGN_DSTK_ERR_DELETE_RANDOM_FOR_VID				2520
#define XSIGN_DSTK_ERR_FILE_SEEK_END						2521
#define XSIGN_DSTK_ERR_FILE_SEEK_BEGIN					    2522
#define XSIGN_DSTK_ERR_FILE_SIZE							2523
#define XSIGN_DSTK_ERR_FILE_CREATE						    2524
                                                            
#define XSIGN_DSTK_ERR_NOT_SIGN_CERT						3000
#define XSIGN_DSTK_ERR_NOT_KM_CERT						    3001
#define XSIGN_DSTK_ERR_MAKE_SIGNED_DATA					    3002
#define XSIGN_DSTK_ERR_WRONG_SIGNED_DATA					3003
#define XSIGN_DSTK_ERR_WRONG_TIME						    3004
#define XSIGN_DSTK_ERR_NOT_EXIST_SIGNER_CERT				3005
#define XSIGN_DSTK_ERR_MAKE_ENVELOPED_DATA				    3006
#define XSIGN_DSTK_ERR_WRONG_ENVELOPED_DATA				    3007
#define XSIGN_DSTK_ERR_WRONG_RECIPIENT_CERTS				3008
#define XSIGN_DSTK_ERR_CERTS_INCLUDE_WRONG_CERT			    3009
#define XSIGN_DSTK_ERR_MAKE_SIGNED_AND_ENVELOPED_DATA	    3010
#define XSIGN_DSTK_ERR_WRONG_SIGNED_AND_ENVELOPED_DATA	    3011
#define XSIGN_DSTK_ERR_WRONG_SIGNER_CERTS				    3012
#define XSIGN_DSTK_ERR_CANNOT_DECRYPT_DATA				    3013
                                                            
#define XSIGN_DSTK_ERR_NOT_EXIST_RANDOM_IN_PRIKEY		    3500
#define XSIGN_DSTK_ERR_NOT_EXIST_VID_IN_CERT				3501
#define XSIGN_DSTK_ERR_INVALID_VID						    3502
                                                            
#define XSIGN_DSTK_ERR_MAKE_GENM							4000
#define XSIGN_DSTK_ERR_WRONG_GENP						    4001
#define XSIGN_DSTK_ERR_MAKE_IR							    4002
#define XSIGN_DSTK_ERR_WRONG_IP							    4003
#define XSIGN_DSTK_ERR_MAKE_KUR							    4004
#define XSIGN_DSTK_ERR_WRONG_KUP							4005
#define XSIGN_DSTK_ERR_MAKE_RR							    4006
#define XSIGN_DSTK_ERR_WRONG_RP							    4007
#define XSIGN_DSTK_ERR_MAKE_CONF							4008
#define XSIGN_DSTK_ERR_CMP_CONNECT						    4009
#define XSIGN_DSTK_ERR_CMP_SEND							    4010
#define XSIGN_DSTK_ERR_CMP_RECV							    4011
#define XSIGN_DSTK_ERR_CMP_REQ_FAILED					    4012
#define XSIGN_DSTK_ERR_EXIST_OTHER_CERT					    4013
#define XSIGN_DSTK_ERR_MAKE_KRR							    4014
#define XSIGN_DSTK_ERR_WRONG_KRP							4015
#define XSIGN_DSTK_ERR_MAKE_PUBKEY_INFO					    4016
#define XSIGN_DSTK_ERR_MAKE_POP							    4017
                                                            
#define XSIGN_DSTK_ERR_EXPORT_PFX						    4500
#define XSIGN_DSTK_ERR_IMPORT_PFX						    4501
#define XSIGN_DSTK_ERR_WRONG_MULTI_CERT					    4502
#define XSIGN_DSTK_ERR_WRONG_MULTI_PRIKEY				    4503
#define XSIGN_DSTK_ERR_DIFFERENT_COUNT					    4504
#define XSIGN_DSTK_ERR_WRONG_PFX_PASSWD					    4505
                                                            
#define XSIGN_DSTK_ERR_INVALID_SYM_ALG					    5000
#define XSIGN_DSTK_ERR_GEN_RANDOM						    5001
#define XSIGN_DSTK_ERR_INVALID_KEY_LEN					    5002
#define XSIGN_DSTK_ERR_INVALID_IV_LEN					    5003
#define XSIGN_DSTK_ERR_NOT_SET_KEY_IV					    5004
#define XSIGN_DSTK_ERR_ENCRYPT_DATA						    5005
#define XSIGN_DSTK_ERR_DECRYPT_DATA						    5006
#define XSIGN_DSTK_ERR_INVALID_HASH_ALG					    5007
#define XSIGN_DSTK_ERR_SIGN								    5008
#define XSIGN_DSTK_ERR_VERIFY_SIGNATURE					    5009
#define XSIGN_DSTK_ERR_DIGEST_DATA						    5010
#define XSIGN_DSTK_ERR_INVALID_MAC_ALG					    5011
#define XSIGN_DSTK_ERR_GEN_MAC							    5012
#define XSIGN_DSTK_ERR_VERIFY_MAC						    5013
#define XSIGN_DSTK_ERR_INVALID_KEY_TYPE					    5014
#define XSIGN_DSTK_ERR_KEY_GENERATE						    5015
#define XSIGN_DSTK_ERR_INVALID_ASYM_ALG					    5016
#define XSIGN_DSTK_ERR_CHECK_KEY_PAIR					    5017
#define XSIGN_DSTK_ERR_GENERATE_KEY_PAIR					5018
#define XSIGN_DSTK_ERR_WRONG_PUBKEY_INFO					5019
#define XSIGN_DSTK_ERR_GEN_SHARED_KEY					    5020
                                                            
#define XSIGN_DSTK_ERR_BASE64_ENCODE						5500
#define XSIGN_DSTK_ERR_BASE64_DECODE						5501
#define XSIGN_DSTK_ERR_PEM_ENCODE							5502
#define XSIGN_DSTK_ERR_PEM_DECODE						    5503
                                                            
#define XSIGN_DSTK_ERR_WRONG_URL							6000
#define XSIGN_DSTK_ERR_INVALID_PROTOCOL					    6001
#define XSIGN_DSTK_ERR_LDAP_INIT							6002
#define XSIGN_DSTK_ERR_LDAP_SIMPLE_BIND_S				    6003
#define XSIGN_DSTK_ERR_LDAP_SET_OPTION					    6004
#define XSIGN_DSTK_ERR_LDAP_SEARCH_S						6005
#define XSIGN_DSTK_ERR_LDAP_FIRST_ENTRY					    6006
#define XSIGN_DSTK_ERR_LDAP_GET_VALUES_LEN				    6007
#define XSIGN_DSTK_ERR_LDAP_NO_DATA						    6008
#define XSIGN_DSTK_ERR_INVALID_DATA_TYPE					6009
#define XSIGN_DSTK_ERR_GET_CRL_FROM_CERT					6010
#define XSIGN_DSTK_ERR_HTTP_CONNCET						    6011
#define XSIGN_DSTK_ERR_HTTP_SEND							6012
#define XSIGN_DSTK_ERR_HTTP_RECV							6013
#define XSIGN_DSTK_ERR_WRONG_PEM_FORMAT					    6014
#define XSIGN_DSTK_ERR_FAIL_READ_CONF_FILE				    6015
#define XSIGN_DSTK_ERR_READ_ENTRY						    6016
#define XSIGN_DSTK_ERR_NOT_EXIST_DSAP_INFO				    6017
#define XSIGN_DSTK_ERR_NOT_EXIST_ISSUER_CERT				6018
#define XSIGN_DSTK_ERR_HTTP_NO_DATA						    6019
                                                            
#define XSIGN_DSTK_ERR_MAKE_SIGNED_CONTENT				    6500
#define XSIGN_DSTK_ERR_WRONG_SIGNED_CONTENT				    6501
#define XSIGN_DSTK_ERR_NOT_SUPPORTED_SIGNER_TYPE			6502
#define XSIGN_DSTK_ERR_MAKE_WAP_ENVELOPED_DATA			    6503
#define XSIGN_DSTK_ERR_WRONG_WAP_ENVELOPED_DATA			    6504
                                                            
#define XSIGN_DSTK_ERR_UNKNOWN_CERT_TYPE					7000
#define XSIGN_DSTK_ERR_UNKNOWN_SIGNDATA_TYPE				7001
#define XSIGN_DSTK_ERR_UNKNOWN_ENVDATA_TYPE				    7002
                                                            
#define XSIGN_DSTK_ERR_WRONG_OBJECTS						7500
#define XSIGN_DSTK_ERR_MAKE_OBJECTS						    7501
#define XSIGN_DSTK_ERR_EXCEED_INDEX						    7502
#define XSIGN_DSTK_ERR_DIFFERENT_DN						    7503
                                                            
#define XSIGN_DSTK_ERR_TOKEN_INIT						    8000
#define XSIGN_DSTK_ERR_GET_SLOT_LIST						8001
#define XSIGN_DSTK_ERR_CRYPTOKI_LIB_INIT					8002
#define XSIGN_DSTK_ERR_SESSION_OPEN						    8003
#define XSIGN_DSTK_ERR_SESSION_CLOSE						8004
#define XSIGN_DSTK_ERR_SO_LOGIN							    8005
#define XSIGN_DSTK_ERR_USER_LOGIN						    8006
#define XSIGN_DSTK_ERR_INIT_PIN							    8007
#define XSIGN_DSTK_ERR_LOG_OUT							    8008
#define XSIGN_DSTK_ERR_FINISH							    8009
#define XSIGN_DSTK_ERR_CHANGE_USER_PIN					    8010
#define XSIGN_DSTK_ERR_FIND_OBJECTS_INIT					8011
#define	XSIGN_DSTK_ERR_FIND_OBJECTS						    8012
#define XSIGN_DSTK_ERR_GET_ATTR_VALUE					    8013
#define XSIGN_DSTK_ERR_SET_ATTR_VALUE					    8014
#define XSIGN_DSTK_ERR_GENERATE_CKA_ID					    8015
#define XSIGN_DSTK_ERR_DESTROY_OBJECT					    8016
#define XSIGN_DSTK_ERR_UNWRAP_KEY						    8017
#define XSIGN_DSTK_ERR_CREATE_OBJECT						8018
#define XSIGN_DSTK_ERR_NOT_EXIST_OBJECT					    8019
#define XSIGN_DSTK_ERR_EXIST_KEY_ID						    8020
#define XSIGN_DSTK_ERR_SESSION_NOT_OPEN						8021
#define XSIGN_DSTK_ERR_WRONG_SIGNATURE_VALUE				8022
#define XSIGN_DSTK_ERR_LIB_MODIFIED						    8023
#define XSIGN_DSTK_ERR_USER_NOT_LOGGED_IN				    8024
#define XSIGN_DSTK_ERR_PIN_INCORRECT						8025
#define XSIGN_DSTK_ERR_DRIVER_INFO_NOT_EXIST				8026
#define XSIGN_DSTK_ERR_SLOT_NOT_LISTED					    8027
#define XSIGN_DSTK_ERR_GET_TOKEN_INFO					    8028
#define XSIGN_DSTK_ERR_DRIVER_PATH_COUNT					8029
                                                            
#define XSIGN_DSTK_ERR_MAKE_TIME_STAMP_REQ				    8500
#define XSIGN_DSTK_ERR_TSP_CONNECT						    8501
#define XSIGN_DSTK_ERR_TSP_SEND							    8502
#define XSIGN_DSTK_ERR_TSP_RECV							    8503
#define XSIGN_DSTK_ERR_WRONG_TIME_STAMP_RES				    8504
#define XSIGN_DSTK_ERR_TSP_REQ_NOT_GRANTED				    8505
#define XSIGN_DSTK_ERR_DIFFERENT_MSG_IMPRINT				8506
#define XSIGN_DSTK_ERR_NOT_PERMITTED_POLICY				    8507
#define XSIGN_DSTK_ERR_WRONG_TIME_STAMP_TOKEN			    8508
#define XSIGN_DSTK_ERR_NOT_EXIST_TSA_CERT				    8509


#define XSIGN_KEYCHAIN_ERR_NOT_INITIALIZED					9100		// KeyChain API 초기화되어 있지 않음
#define XSIGN_KEYCHAIN_ERR_MALLOC							9101		// 메모리 할당 실패
#define XSIGN_KEYCHAIN_ERR_DATA_EMPTY						9102		// 획득한 값이 비어있음
#define XSIGN_KEYCHAIN_ERR_PRIKEY_FORMAT					9103		// 순수 개인키 정보가 아님 (즉, 암호화된 개인키 정보)

#define XSIGN_KEYCHAIN_ERR_SEC_UNIMPLEMENTED				9200		// OSStatus : errSecUnimplemented 발생
#define XSIGN_KEYCHAIN_ERR_SEC_PARAM						9201		// OSStatus : errSecParam 발생
#define XSIGN_KEYCHAIN_ERR_SEC_ALLOCATE						9202		// OSStatus : errSecAllocate 발생
#define XSIGN_KEYCHAIN_ERR_SEC_NOT_AVAILABLE				9203		// OSStatus : errSecNotAvailable 발생
#define XSIGN_KEYCHAIN_ERR_SEC_DUPLICATEDITEM				9204		// OSStatus : errSecDuplicateItem 발생
#define XSIGN_KEYCHAIN_ERR_SEC_ITEM_NOT_FOUND				9205		// OSStatus : errSecItemNotFound 발생
#define XSIGN_KEYCHAIN_ERR_SEC_INTERACTION_NOT_ALLOWED		9206		// OSStatus : errSecInteractionNotAllowed 발생
#define XSIGN_KEYCHAIN_ERR_SEC_DECODE						9207		// OSStatus : errSecDecode 발생
#define XSIGN_KEYCHAIN_ERR_SEC_UNKNOWN						9208		// OSStatus : 알수없는 OSStatus 값
#define XSIGN_KEYCHAIN_ERR_SEC_CERT_CREATE_WITH_DATA		9209		// SecCertificateCreateWithData 의 리턴값이 NULL
#define XSIGN_KEYCHAIN_ERR_SEC_TRUST_COPY_PUBKEY			9210		// SecTrustCopyPublicKey 의 리턴값이 NULL
#define XSIGN_KEYCHAIN_ERR_NOT_SUPPORTED					9900		// KeyChain 을 지원하지 않는 함수




#endif /* !defined(___DSTOOLKIT_IPHONE_ERRCODE_H___) */

