<!--#include virtual="/api/include/utf8.asp"-->
<%
	SITE = InjRequest("SITE")
	Dim LINK_DOMAINURL

	Select Case SITE
		Case "BBQ"
			LINK_DOMAINURL = SITE_DOMAINURL_BBQ
		Case "HAPPY"
			LINK_DOMAINURL = SITE_DOMAINURL_HAPPY
		Case "CKPLACE"
			LINK_DOMAINURL = SITE_DOMAINURL_CKPLACE
		Case "BARBECUE"
			LINK_DOMAINURL = SITE_DOMAINURL_BARBECUE
		Case "UNINE"
			LINK_DOMAINURL = SITE_DOMAINURL_UNINE
		Case "ALLTOKK"
			LINK_DOMAINURL = SITE_DOMAINURL_ALLTOKK
		Case "BELIEF"
			LINK_DOMAINURL = SITE_DOMAINURL_BELIEF
		Case "WATAMI"
			LINK_DOMAINURL = SITE_DOMAINURL_WATAMI
		Case "CHICKEN_UNI"
			LINK_DOMAINURL = SITE_DOMAINURL_CHICKEN_UNI
		Case "START"
			LINK_DOMAINURL = SITE_DOMAINURL_START
		Case "GLOBAL"
			LINK_DOMAINURL = SITE_DOMAINURL_GLOBAL
		Case "GROUP"
			LINK_DOMAINURL = SITE_DOMAINURL_GROUP
		Case "MBBQ"
			LINK_DOMAINURL = MSITE_DOMAINURL_BBQ
		Case "MHAPPY"
			LINK_DOMAINURL = MSITE_DOMAINURL_HAPPY
		Case "MCKPLACE"
			LINK_DOMAINURL = MSITE_DOMAINURL_CKPLACE
		Case "MBARBECUE"
			LINK_DOMAINURL = MSITE_DOMAINURL_BARBECUE
		Case "MUNINE"
			LINK_DOMAINURL = MSITE_DOMAINURL_UNINE
		Case "MALLTOKK"
			LINK_DOMAINURL = MSITE_DOMAINURL_ALLTOKK
		Case "MBELIEF"
			LINK_DOMAINURL = MSITE_DOMAINURL_BELIEF
		Case "MWATAMI"
			LINK_DOMAINURL = MSITE_DOMAINURL_WATAMI
		Case "MCHICKEN_UNI"
			LINK_DOMAINURL = MSITE_DOMAINURL_CHICKEN_UNI
		Case "MSTART"
			LINK_DOMAINURL = MSITE_DOMAINURL_START
		Case "MGLOBAL"
			LINK_DOMAINURL = MSITE_DOMAINURL_GLOBAL
		Case "MGROUP"
			LINK_DOMAINURL = MSITE_DOMAINURL_GROUP
		Case "BBQMALL"
			LINK_DOMAINURL = SITE_DOMAINURL_BBQMALL
		Case Else
			LINK_DOMAINURL = "/"
	End Select

	If LINK_DOMAINURL = "NO" Then 
		Response.Write "{""result"":0,""url"":"""& LINK_DOMAINURL &"""}"
	ElseIf LINK_DOMAINURL = "/" Then 
		Response.Write "{""result"":1,""url"":"""& LINK_DOMAINURL &"""}"
	Else
		If SITE = "BBQMALL" Or SITE = "WATAMI" Or SITE ="MWATAMI" Then
			Response.Write "{""result"":3,""url"":"""& LINK_DOMAINURL &"""}"
		Else 
			LINK_DOMAINURL = LINK_DOMAINURL & "/api/loginCheck.asp"
			Response.Write "{""result"":2,""url"":"""& LINK_DOMAINURL &"""}"
		End If
'		access_token = Session("access_token")
'		If Not FncIsBlank(access_token) Then 
'			LINK_DOMAINURL = LINK_DOMAINURL & "/api/loginCheck.asp?access_token=" & access_token
'			TokenRst = SendXMLHTTP(URL)
'			Response.Write "{""result"":2,""url"":"""& LINK_DOMAINURL &"""}"
'		Else 
'			Response.Write "{""result"":2,""url"":"""& LINK_DOMAINURL &"""}"
'		End If
	End If
%>